### ISSUE TITLE
Produces pub_key values different than CLI, so different signatures

### ISSUE THREAD

**Issue by farukterzioglu** [cosmos/sig#7]
cosmos/sig library produces pub_key values different than CLI, so different signatures. 
Because of that CLI doesn't accept transactions signed with cosmos/sig. (exception: 'signature verification failed; verify correct account sequence and chain-id')  

Output from cosmos/sig
```
{"msg":[....,"signatures":[{"signature":"....","pub_key":{"type":"...","value":"A5Jc4oaS4/45sJpB/2iLAUPe45QKnyOebVaRiVjzUaIe"}}]}
```

Output from CLI
```
{"msg":[....."signatures":[{"signature":"....","pub_key":{"type":"...","value":"AgntYTQfdcBo24joKZW6qrMoAvga3/IAKwu6X6cfTtMA"}}]}}
```

mnemonic that creates the wallet with cosmos/sig
```
const mnemonic = "cloth tower certain forget city autumn better ankle that village bulk torch error edit cement dilemma palace soldier system around arrest similar lab luggage";
const wallet = Sig.createWalletFromMnemonic(mnemonic, "12345678");
```

Generated key from CLI;
```
- name: signtest
  type: local
  address: cosmos17yj45mrgvwezj9jlnhcgd2wr33ufqlcflj0xxv
  pubkey: cosmospub1addwnpepqgy76cf5ra6uq6xm3r5zn9d642ejsqhcrt0lyqptpwa9lfclfmfsqqvgyhj
  ....
cloth tower certain forget city autumn better ankle that village bulk torch error edit cement dilemma palace soldier system around arrest similar lab luggage

passphrase : 12345678
```

sign cli command I use
```
gaiacli tx send cosmos17yj45mrgvwezj9jlnhcgd2wr33ufqlcflj0xxv cosmos1vfknyaz4fgrkj8ef87ute57gfscmg3ukprjmqh  100umuon --memo testing --generate-only > unsigned.json
gaiacli tx sign unsigned.json --from signtest --chain-id gaia-13007 --account-number 17150 --sequence 6 --offline
```

**Comment by farukterzioglu** [comment]
It looks like if you don't set password for  Sig.createWalletFromMnemonic, it works as expected. e.g. 
Sig.createWalletFromMnemonic(mnemonic);

But password is optional and if you set it, it won't produce same priv/pub key pair with CLI, so it will produce different signatures which can not be broadcasted. 

I am keeping this issue open because optional parameter 'password' causes to fail for signing.

**Comment by yzhanginwa** [comment]
Which version is your cosmos-sdk? I have signature related issues after upgrading from 0.37.4 to 0.38.0.
